apiVersion: v1
kind: Namespace
metadata:
  name: demo
 
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: demo-rabbitmqcluster
  namespace: demo
spec:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 800m
      memory: 1Gi
  rabbitmq:
    additionalConfig: |
      default_user=guest
      default_pass=guest
