apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: producer
  name: producer
spec:
  containers:
  - image: metiii/do_producer:v1.9
    name: producer
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
