---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbit-pod-autoscaler
rules:
  - apiGroups: ["*"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbit-pod-autoscaler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rabbit-pod-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rabbit-pod-autoscaler
subjects:
  - kind: ServiceAccount
    name: rabbit-pod-autoscaler
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-pod-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-pod-autoscaler
  template:
    metadata:
      labels:
        app: rabbit-pod-autoscaler
    spec:
      serviceAccountName: rabbit-pod-autoscaler
      containers:
        - name: rabbit-pod-autoscaler
          image: onfido/k8s-rabbit-pod-autoscaler
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          env:
            - name: INTERVAL
              value: "15"
            - name: RABBIT_HOST
              value: "demo-rabbitmqcluster.demo"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASS
              value: "guest"
            - name: AUTOSCALING
              value: >
                1|5|6|default|worker|demo_queue
            - name: LOGS
              value: HIGH

